### ISSUE TITLE
Good Job, but how to reduce the apk size?

### ISSUE THREAD

**Issue by FazliMolaJan** [rrifafauzikomara/FlutterVSNative#1]

**Comment by rrifafauzikomara** [comment]
You can reduce the APK size when you want to publish it on the Play Store using the App Bundle.

This is my example of that:
* [Repository](https://github.com/rrifafauzikomara/MovieCatalogue)
* [Play Store](https://play.google.com/store/apps/details?id=id.rifafauzi.movie)

The APK from Play Store is 6,5 MB
